"""empty message

Revision ID: 7715619cc976
Revises: cc274bcd0f0c
Create Date: 2019-08-27 19:14:28.464974

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7715619cc976'
down_revision = 'cc274bcd0f0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('article_id', sa.Integer(), nullable=True))
    op.add_column('comment', sa.Column('time', sa.DateTime(), nullable=True))
    op.add_column('comment', sa.Column('username', sa.String(length=30), nullable=True))
    op.drop_constraint('comment_ibfk_1', 'comment', type_='foreignkey')
    op.create_foreign_key(None, 'comment', 'article', ['article_id'], ['id'])
    op.drop_column('comment', 'article')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('article', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.create_foreign_key('comment_ibfk_1', 'comment', 'article', ['article'], ['id'])
    op.drop_column('comment', 'username')
    op.drop_column('comment', 'time')
    op.drop_column('comment', 'article_id')
    # ### end Alembic commands ###
