"""empty message

Revision ID: cc274bcd0f0c
Revises: d8737f42faa0
Create Date: 2019-08-27 19:10:15.459052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc274bcd0f0c'
down_revision = 'd8737f42faa0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.String(length=300), nullable=True),
    sa.Column('article', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article'], ['article.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    # ### end Alembic commands ###
