"""empty message

Revision ID: d35400d15fc8
Revises: 3807caa38d4b
Create Date: 2019-08-31 16:14:30.948142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd35400d15fc8'
down_revision = '3807caa38d4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_user', sa.Column('name', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_user', 'name')
    # ### end Alembic commands ###
