"""empty message

Revision ID: dd8e4b85d70b
Revises: 983a5b82d4b7
Create Date: 2019-08-27 09:06:00.071216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd8e4b85d70b'
down_revision = '983a5b82d4b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('title', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'title')
    # ### end Alembic commands ###
