"""empty message

Revision ID: e9b083aeec68
Revises: 6f0366453960
Create Date: 2019-08-26 22:14:27.512500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9b083aeec68'
down_revision = '6f0366453960'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('ab', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'ab')
    # ### end Alembic commands ###
